---
- name: Check server status
  hosts: localhost
  gather_facts: yes
  become: false

  tasks:
    - name: Check uptime
      ansible.builtin.command: uptime
      register: uptime_result

    - name: Display uptime
      ansible.builtin.debug:
        msg: "Uptime for {{ inventory_hostname }}: {{ uptime_result.stdout }}"

    - name: Check disk usage
      ansible.builtin.command: df -h /
      register: disk_result

    - name: Display disk usage
      ansible.builtin.debug:
        msg: "Disk usage on {{ inventory_hostname }}: {{ disk_result.stdout_lines[1] }}"

    - name: Check memory usage
      ansible.builtin.command: free -h
      register: mem_result

    - name: Display memory usage
      ansible.builtin.debug:
        msg: "Memory usage on {{ inventory_hostname }}: {{ mem_result.stdout_lines[1] }}"

    - name: Check if SSH port is open
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 5
      register: ssh_port

    - name: Display SSH port status
      ansible.builtin.debug:
        msg: "SSH port reachable on {{ inventory_hostname }}: {{ ssh_port.state == 'started' }}"

